### ISSUE TITLE
Read parquet error

### ISSUE THREAD

**Issue by quartox** [dask/dask-yarn#54]
Error trying to read a parquet file. Looks like the useful info is the first few lines, but I can't parse it. Any direction would help.

```
2019-02-19 09:46:43.006328, p43349, th140597036791616, ERROR Failed to invoke RPC call "getFsStats" on server "namenode:8020": 
RpcChannel.cpp: 483: HdfsRpcException: Failed to invoke RPC call "getFsStats" on server "namenode:8020"
Caused by
RpcChannel.cpp: 931: HdfsRpcServerException: org.apache.hadoop.security.authorize.AuthorizationException: User: jlord is not allowed to impersonate 1�H�M�dH3
             %(

2019-02-19 09:46:43.006434, p43349, th140597036791616, INFO Retry idempotent RPC call "getFsStats" on server "namenode:8020"
Traceback (most recent call last):
  File "simple.py", line 19, in <module>
    df = dataframe.read_parquet('hdfs:///user/hive/warehouse/dra_sanity_tests.db/test_excavator')
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1145, in read_parquet
    storage_options=storage_options
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/bytes/core.py", line 354, in get_fs_token_paths
    fs, fs_token = get_fs(protocol, options)
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/bytes/core.py", line 513, in get_fs
    fs = cls(**storage_options)
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/bytes/hdfs3.py", line 15, in __init__
    self.fs = hdfs3.HDFileSystem(**kwargs)
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/hdfs3/core.py", line 76, in __init__
    self.connect()
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/hdfs3/core.py", line 141, in connect
    raise ConnectionError('Connection Failed: {}'.format(msg))
ConnectionError: Connection Failed: HdfsRpcException: Failed to invoke RPC call "getFsStats" on server "namenode:8020"	Caused by: HdfsRpcServerException: org.apache.hadoop.security.authorize.AuthorizationException: User: jlord is not allowed to impersonate 1�H�M�dH3
                                                           %(
```

**Comment by jcrist** [comment]
I can't say for certain, but my guess is this is due to hdfs3 not being a very robust hdfs client. I recommend using pyarrow instead in most situations, and Dask will use pyarrow by default if it's available.

```python
conda install pyarrow -y
conda uninstall hdfs3 -y
```

**Comment by quartox** [comment]
Updated to the latest pyarrow 0.12, removed hdfs3 and now get

```
  File "simple.py", line 19, in <module>
    df = dataframe.read_parquet('hdfs:///user/jlord/test_lots_of_parquet', engine='pyarrow')
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1145, in read_parquet
    storage_options=storage_options
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/bytes/core.py", line 354, in get_fs_token_paths
    fs, fs_token = get_fs(protocol, options)
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/bytes/core.py", line 513, in get_fs
    fs = cls(**storage_options)
  File "/nas/isg_prodops_work/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/bytes/pyarrow.py", line 35, in __init__
    self.fs = pa.hdfs.HadoopFileSystem(update_hdfs_options(**kwargs))
TypeError: update_hdfs_options() missing 1 required positional argument: 'options'
```

A colleague is trying fastparquet, but wanted to mention in case it is useful. I can repost in dask since it looks like that is where the error is originating from.

**Comment by jcrist** [comment]
This issue is already fixed on master, try installing dask from github:

```
conda uninstall dask -y
pip install git+https://github.com/dask/dask.git
```

**Comment by quartox** [comment]
Working with master.
