### ISSUE TITLE
Trouble reading with KMS

### ISSUE THREAD

**Issue by quartox** [dask/dask-yarn#55]
The Hadoop cluster I use just added additional security with two KMS servers to encrypt the data. From the logs it looks like the KMS is unhappy with my kerberos credentials. I do have a valid kerberos ticket (the job would not have launched otherwise but I double checked).

I am getting a new error while reading from parquet:

```
19/03/01 12:16:45 INFO skein.Driver: Driver started, listening on 46336
19/03/01 12:16:46 INFO hdfs.DFSClient: Created token for jlord: HDFS_DELEGATION_TOKEN owner=jlord@AD.ALLSTATE.COM, renewer=yarn, realUser=, issueDate=1551464206344, maxDate=1552069006344, sequenceNumber=9382869, masterKeyId=510 on ha-hdfs:nameservice1
19/03/01 12:16:47 INFO security.TokenCache: Got dt for hdfs://nameservice1; Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:nameservice1, Ident: (token for jlord: HDFS_DELEGATION_TOKEN owner=jlord@AD.ALLSTATE.COM, renewer=yarn, realUser=, issueDate=1551464206344, maxDate=1552069006344, sequenceNumber=9382869, masterKeyId=510)
19/03/01 12:16:47 INFO security.TokenCache: Got dt for hdfs://nameservice1; Kind: kms-dt, Service: 10.195.102.124:16000, Ident: (kms-dt owner=jlord, renewer=yarn, realUser=, issueDate=1551464207669, maxDate=1552069007669, sequenceNumber=115244, masterKeyId=35)
19/03/01 12:16:47 INFO skein.Driver: Uploading application resources to hdfs://nameservice1/user/jlord/.skein/application_1551067831607_22507
19/03/01 12:17:03 INFO skein.Driver: Submitting application...
19/03/01 12:17:03 INFO impl.YarnClientImpl: Submitted application application_1551067831607_22507
19/03/01 12:17:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "read_parquet.py", line 27, in <module>
    df = dataframe.read_parquet('hdfs:///user/jlord/test_lots_of_parquet')
  File "/nas/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1155, in read_parquet
    categories=categories, index=index, infer_divisions=infer_divisions)
  File "/nas/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 674, in _read_pyarrow
    filters=filters)
  File "/nas/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/pyarrow/parquet.py", line 890, in __init__
    path_or_paths, self.fs, metadata_nthreads=metadata_nthreads)
  File "/nas/jlord/conda/envs/dask-yarn/lib/python3.7/site-packages/pyarrow/parquet.py", line 1065, in _make_manifest
    .format(path))
OSError: Passed non-file path: /user/jlord/test_lots_of_parquet
19/03/01 12:17:54 INFO skein.Driver: Driver shut down
```

The logs:

```
Container: container_e10_1551067831607_22507_01_000001 on all1.allstate.com_8041
=====================================================================================
LogType:application.master.log
Log Upload Time:Fri Mar 01 12:17:55 -0600 2019
LogLength:3334
Log Contents:
19/03/01 12:17:09 INFO skein.ApplicationMaster: Running as user jlord
19/03/01 12:17:09 INFO skein.ApplicationMaster: Application specification successfully loaded
19/03/01 12:17:10 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/03/01 12:17:11 INFO skein.ApplicationMaster: gRPC server started at all1.allstate.com:41971
19/03/01 12:17:11 INFO skein.ApplicationMaster: WebUI server started at all1.allstate.com:34551
19/03/01 12:17:11 INFO skein.ApplicationMaster: Registering application with resource manager
19/03/01 12:17:12 INFO skein.ApplicationMaster: Initializing service 'dask.worker'.
19/03/01 12:17:12 INFO skein.ApplicationMaster: Initializing service 'dask.scheduler'.
19/03/01 12:17:12 INFO skein.ApplicationMaster: REQUESTED: dask.scheduler_0
19/03/01 12:17:13 INFO skein.ApplicationMaster: Starting container_e10_1551067831607_22507_01_000002...
19/03/01 12:17:13 INFO skein.ApplicationMaster: RUNNING: dask.scheduler_0 on container_e10_1551067831607_22507_01_000002
19/03/01 12:17:52 INFO skein.ApplicationMaster: Scaling service 'dask.worker' to 10 instances, a delta of 10.
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_0
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_1
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_2
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_3
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_4
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_5
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_6
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_7
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_8
19/03/01 12:17:52 INFO skein.ApplicationMaster: REQUESTED: dask.worker_9
19/03/01 12:17:54 INFO skein.ApplicationMaster: Shutting down: Shutdown requested by user.
19/03/01 12:17:54 INFO skein.ApplicationMaster: Unregistering application with status SUCCEEDED
19/03/01 12:17:54 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
19/03/01 12:17:54 WARN security.UserGroupInformation: PriviledgedActionException as:jlord (auth:KERBEROS) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
19/03/01 12:17:54 WARN ipc.Client: Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
19/03/01 12:17:54 WARN security.UserGroupInformation: PriviledgedActionException as:jlord (auth:KERBEROS) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
19/03/01 12:17:54 INFO skein.ApplicationMaster: Deleted application directory hdfs://nameservice1/user/jlord/.skein/application_1551067831607_22507
19/03/01 12:17:54 INFO skein.ApplicationMaster: WebUI server shut down
19/03/01 12:17:54 INFO skein.ApplicationMaster: gRPC server shut down

LogType:container-localizer-syslog
Log Upload Time:Fri Mar 01 12:17:55 -0600 2019
LogLength:2442
Log Contents:
2019-03-01 12:17:06,120 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:SIMPLE) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
2019-03-01 12:17:06,122 WARN [ContainerLocalizer Downloader] org.apache.hadoop.ipc.Client: Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
2019-03-01 12:17:06,122 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:SIMPLE) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
2019-03-01 12:17:07,687 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:KERBEROS) cause:org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
2019-03-01 12:17:07,688 WARN [ContainerLocalizer Downloader] org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider: KMS provider at [https://all2.allstate.com:16000/kms/v1/] threw an IOException [org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]!!
2019-03-01 12:17:08,483 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:KERBEROS) cause:org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
2019-03-01 12:17:08,485 WARN [ContainerLocalizer Downloader] org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider: KMS provider at [https://all2.allstate.com:16000/kms/v1/] threw an IOException [org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]!!



Container: container_e10_1551067831607_22507_01_000002 on all1753.allstate.com_8041
=====================================================================================
LogType:container-localizer-syslog
Log Upload Time:Fri Mar 01 12:17:55 -0600 2019
LogLength:2442
Log Contents:
2019-03-01 12:17:17,341 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:SIMPLE) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
2019-03-01 12:17:17,347 WARN [ContainerLocalizer Downloader] org.apache.hadoop.ipc.Client: Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
2019-03-01 12:17:17,348 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:SIMPLE) cause:org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
2019-03-01 12:17:19,085 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:KERBEROS) cause:org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
2019-03-01 12:17:19,088 WARN [ContainerLocalizer Downloader] org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider: KMS provider at [https://all2.allstate.com:16000/kms/v1/] threw an IOException [org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]!!
2019-03-01 12:17:51,257 WARN [ContainerLocalizer Downloader] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jlord (auth:KERBEROS) cause:org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
2019-03-01 12:17:51,257 WARN [ContainerLocalizer Downloader] org.apache.hadoop.crypto.key.kms.LoadBalancingKMSClientProvider: KMS provider at [https://all2.allstate.com:16000/kms/v1/] threw an IOException [org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]!!

LogType:dask.scheduler.log
Log Upload Time:Fri Mar 01 12:17:55 -0600 2019
LogLength:633
Log Contents:
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://10.195.102.137:38407
distributed.scheduler - INFO -       bokeh at:                    :36105
distributed.scheduler - INFO - Receive client connection: Client-543b1970-3c4e-11e9-9f37-246e9682cec8
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove client Client-543b1970-3c4e-11e9-9f37-246e9682cec8
distributed.scheduler - INFO - Remove client Client-543b1970-3c4e-11e9-9f37-246e9682cec8
distributed.scheduler - INFO - Close client connection: Client-543b1970-3c4e-11e9-9f37-246e9682cec8
```

**Comment by jcrist** [comment]
Hmmm, I'm seeing two things here:

- The error from pyarrow not being able to read your files
- The warnings in the skein logs like `"Operation category READ is not supported in state standby"`

The first one I'm not sure about. The first thing I'd try is to see if you can read them using Dask locally without dask-yarn (just using the default scheduler on an edge node). Something like:

```python
import dask.dataframe as dd
ddf = dd.read_parquet(...)
ddf.head()
```

The second ones show up in HA mode and are likely innocuous, but may be indicative of another separate issue.

**Comment by quartox** [comment]
I get the exact same error doing a dask local read of the file. Specifically: `df = dataframe.read_parquet('hdfs:///user/jlord/test_lots_of_parquet')`

So this suggests arrow is not able to communicate with the KMS? We have had problems with open source spark (the vended version of spark works) where the hdfs-site.xml and core-site.xml don't list the two servers as different values and spark tries to contact a KMS server called `server1;server2`, but it looks like arrow is parsing the server names correctly. Should repost this issue over on the arrow github?

I believe I have seen the `"Operation category READ is not supported in state standby"` before when it was working but it is hard to know for sure.

**Comment by jcrist** [comment]
Apologies for the late reply. Yeah, this looks like a pyarrow issue, I'd forward this issue along to there, along with a reproducible example using just the pyarrow api (untested):

```python
from pyarrow import hdfs

fs = hdfs.connect()
with fs.open("/user/jlord/test_file.parq", "rb") as fil:
    _ = fil.read()
```

**Comment by quartox** [comment]
For anyone else reading this https://github.com/apache/arrow/issues/3902

**Comment by jcrist** [comment]
Closing this for now, please let me know if you run into any other issues.

**Comment by quartox** [comment]
For reference, this was a hadoop `CLASSPATH` environment variable problem. See https://arrow.apache.org/docs/python/filesystems.html
