### ISSUE TITLE
Amazon EMR bootstrap failing for workers

### ISSUE THREAD

**Issue by nmerket** [dask/dask-yarn#75]
I'm following the instructions for [deploiying on EMR](http://yarn.dask.org/en/latest/aws-emr.html) and using the `bootstrap-dask` script with no modifications from this repo. I'm able to successfully connect to the jupyter notebook server and create a `YarnCluster`. However, when I try to add workers to the cluster they never successfully start. Looking at the Skein logs, it looks like it's trying to start containers, but they are all failing with the following message:

```
Traceback (most recent call last):
  File "/mnt3/yarn/usercache/hadoop/appcache/application_1561654916149_0001/container_1561654916149_0001_01_000002/environment/bin/dask-yarn", line 7, in <module>
    from dask_yarn.cli import main
  File "/mnt3/yarn/usercache/hadoop/appcache/application_1561654916149_0001/container_1561654916149_0001_01_000002/environment/lib/python3.6/site-packages/dask_yarn/cli.py", line 17, in <module>
    from distributed.cli.utils import install_signal_handlers, uri_from_host_port
ImportError: cannot import name 'uri_from_host_port'
```

Here is the results of a `pip freeze`

```
asn1crypto==0.24.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
bokeh==1.2.0
boto3==1.9.162
botocore==1.12.163
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.1.1
conda==4.7.5
conda-pack==0.3.1
conda-package-handling==1.3.10
cryptography==2.7
cytoolz==0.9.0.1
dask==2.0.0
dask-yarn==0.6.0
decorator==4.4.0
defusedxml==0.6.0
distributed==2.0.1
docutils==0.14
entrypoints==0.3
grpcio==1.16.1
heapdict==1.0.0
idna==2.8
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
Jinja2==2.10.1
jmespath==0.9.4
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
libarchive-c==2.8
locket==0.2.0
MarkupSafe==1.1.1
mistune==0.8.4
msgpack==0.6.1
nbconvert==5.5.0
nbformat==4.4.0
nbserverproxy==0.8.8
notebook==5.7.8
numpy==1.16.4
olefile==0.46
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
partd==0.3.10
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.0.0
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.8.0
psutil==5.6.2
ptyprocess==0.6.0
pyarrow==0.11.1
pycosat==0.6.3
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrsistent==0.14.11
PySocks==1.7.0
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1
pyzmq==18.0.0
requests==2.22.0
ruamel-yaml==0.15.46
s3fs==0.2.1
s3transfer==0.2.0
Send2Trash==1.5.0
six==1.12.0
skein==0.7.3
sortedcontainers==2.1.0
tblib==1.4.0
terminado==0.8.2
testpath==0.4.2
toolz==0.9.0
tornado==6.0.2
tqdm==4.32.1
traitlets==4.3.2
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
zict==0.1.4
```

**Comment by jcrist** [comment]
This is due to the recent distributed release making some backwards-incompatible changes. The fix is in #74. Will hopefully get a new release out soon.

For now, you can update your boostrap action script to pin distributed to `< 2.0`.

**Comment by jcrist** [comment]
Version 0.6.1 has now been released (available on PyPI, soon on conda-forge). Updating should fix your issue.

**Comment by nmerket** [comment]
Awesome. Thanks for the fast turnaround on this.
