### ISSUE TITLE
0.7.0 Still breaks with Distributed 2.2.0

### ISSUE THREAD

**Issue by bschreck** [dask/dask-yarn#92]
Some issues with the nanny. Workers start up and then quickly fail.

```
cluster = YarnCluster(n_workers=1, deploy_mode='local')
client = Client(cluster)
```
Logs:
```
Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1564782225613_0002/container_1564782225613_0002_01_000002/environment/bin/dask-yarn", line 11, in <module>
    sys.exit(main())
  File "/mnt/yarn/usercache/hadoop/appcache/application_1564782225613_0002/container_1564782225613_0002_01_000002/environment/lib/python3.6/site-packages/dask_yarn/cli.py", line 412, in main
    func(**kwargs)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1564782225613_0002/container_1564782225613_0002_01_000002/environment/lib/python3.6/site-packages/dask_yarn/cli.py", line 379, in worker
    loop.run_sync(run)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1564782225613_0002/container_1564782225613_0002_01_000002/environment/lib/python3.6/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/mnt/yarn/usercache/hadoop/appcache/application_1564782225613_0002/container_1564782225613_0002_01_000002/environment/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1564782225613_0002/container_1564782225613_0002_01_000002/environment/lib/python3.6/site-packages/dask_yarn/cli.py", line 374, in run
    yield worker._start(None)
AttributeError: 'Nanny' object has no attribute '_start'
```

- **Version information**

    Please include version information for the following:

    - Python version (``python --version``) 3.6.9
    - Dask-Yarn version (``dask-yarn --version``) 0.7.0
    - Hadoop version, and distribution (e.g. CDH) if applicable: EMR

**Comment by mrocklin** [comment]
That code doesn't seem to be in the latest release.  I suspect that you
still have an older version lying around.

**Comment by bschreck** [comment]
hmm I guess I never explicitly checked what version of distributed I had running, just assumed it was 2.2.0 because I had dask-yarn 0.7.0, which depends on distributed>=2.2.0.

When I explicitly set distributed==2.1.0 it worked fine

**Comment by jcrist** [comment]
> just assumed it was 2.2.0 because I had dask-yarn 0.7.0, which depends on distributed>=2.2.0.

You definitely don't have `dask-yarn` 0.7.0, because the code in your traceback is from an older version, and no longer exists in the lastest release. For example, your traceback points at line 374 in `cli.py`, which in the latest release is https://github.com/dask/dask-yarn/blob/a6aca36284e6ae78d951fc12536678a8cb784334/dask_yarn/cli.py#L374.

I suspect you have an older version of `dask-yarn` around, perhaps in a packaged environment.

**Comment by bschreck** [comment]
You must have been right. However, my new error after creating a fresh cluster is all websocket related. I replied in the more relevant thread: https://github.com/dask/dask-yarn/issues/80#issuecomment-518452242

**Comment by jcrist** [comment]
Glad to hear it, closing.
